name       : activate-linux
version    : 1.1.0
release    : 3
source     :
    - https://github.com/MrGlockenspiel/activate-linux/archive/refs/tags/v1.1.0.tar.gz : cf892c90a57bf6026f777715207aa7066fc7c4940da39d62a6c24b51a726786d
license    : GPL-3.0-or-later
homepage   : https://github.com/MrGlockenspiel/activate-linux
component  : desktop
summary    : The "Activate Windows" watermark ported to Linux
clang      : yes
description: |
    The "Activate Windows" watermark ported to Linux 
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x11)
    - pkgconfig(xfixes)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xt)
build      : |
    %make
install    : |
    install -Dm00644 activate-linux.1 $installdir/usr/share/man/man1/activate-linux.1
    install -Dm00755 activate-linux $installdir/usr/bin/activate-linux
